<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('cars')->insert([
            [
                'name' => 'Toyota Corolla',
                'brand' => 'Toyota',
                'model' => 'Corolla',
                'year' => 2020,
                'car_type' => 'Sedan',
                'daily_rent_price' => 45.00,
                'availability' => true,
                'image' => 'cars/toyota_corolla.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Honda Civic',
                'brand' => 'Honda',
                'model' => 'Civic',
                'year' => 2019,
                'car_type' => 'Sedan',
                'daily_rent_price' => 50.00,
                'availability' => true,
                'image' => 'cars/honda_civic.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ford Mustang',
                'brand' => 'Ford',
                'model' => 'Mustang',
                'year' => 2021,
                'car_type' => 'Coupe',
                'daily_rent_price' => 120.00,
                'availability' => false,
                'image' => 'cars/ford_mustang.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chevrolet Suburban',
                'brand' => 'Chevrolet',
                'model' => 'Suburban',
                'year' => 2022,
                'car_type' => 'SUV',
                'daily_rent_price' => 95.00,
                'availability' => true,
                'image' => 'cars/chevrolet_suburban.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tesla Model 3',
                'brand' => 'Tesla',
                'model' => 'Model 3',
                'year' => 2023,
                'car_type' => 'Sedan',
                'daily_rent_price' => 100.00,
                'availability' => true,
                'image' => 'cars/tesla_model3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hyundai Tucson',
                'brand' => 'Hyundai',
                'model' => 'Tucson',
                'year' => 2020,
                'car_type' => 'SUV',
                'daily_rent_price' => 60.00,
                'availability' => false,
                'image' => 'cars/hyundai_tucson.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kia Sportage',
                'brand' => 'Kia',
                'model' => 'Sportage',
                'year' => 2021,
                'car_type' => 'SUV',
                'daily_rent_price' => 65.00,
                'availability' => true,
                'image' => 'cars/kia_sportage.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nissan Altima',
                'brand' => 'Nissan',
                'model' => 'Altima',
                'year' => 2018,
                'car_type' => 'Sedan',
                'daily_rent_price' => 40.00,
                'availability' => true,
                'image' => 'cars/nissan_altima.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'BMW X5',
                'brand' => 'BMW',
                'model' => 'X5',
                'year' => 2022,
                'car_type' => 'SUV',
                'daily_rent_price' => 110.00,
                'availability' => true,
                'image' => 'cars/bmw_x5.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mercedes-Benz C-Class',
                'brand' => 'Mercedes-Benz',
                'model' => 'C-Class',
                'year' => 2021,
                'car_type' => 'Sedan',
                'daily_rent_price' => 115.00,
                'availability' => false,
                'image' => 'cars/mercedes_c_class.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
